prepare:
  random_seed: 42

split:
  test_size: 0.2
  random_state: 42

train:
  model_type: RandomForestRegressor
  n_estimators: 200
  max_depth: 10
  random_state: 42

evaluate:
  metric: r2_score
